### ISSUE TITLE
DMCA Request: "I Need You" by Megaphonix

### ISSUE THREAD

**Issue by scottg96** [elliotttate/beatsaver-laravel#64]
To Whom It May Concern:

I'm writing in regards to a chart and song download on Beat Saver of my exclusive PSVR track in Beat Saber, "I Need You", located at the following link: https://beatsaver.com/browse/detail/10369-10893

Specifically, the sound recording (in the form of a "song.ogg" file within the downloaded folder) is my protected work via Beat Games/BMI and should not be distributed freely without proper distribution licensing and royalty collection.

I have a good faith belief that use of the material in the manner complained of is not authorized by myself or Beat Games; and I also certify that the information in this notification is accurate, and under penalty of perjury, that I am authorized to act on behalf of the owner of the copyright that is allegedly infringed.

If you have any further questions, I can be reached at scott@megaphonix.com, and my phone number is (201) 788-0790.

Thank you,
Scott Greene

**Comment by elliotttate** [comment]
Hey Scott, thanks for letting us know! The map has been removed and we've gotten in contact with the uploader (great job on the music btw, I'm a huge fan!)

**Comment by scottg96** [comment]
Thanks Elliott - by the way, I come in peace, I just want to make sure I'm getting my fair share through legit song downloads or streams 😉 Plus, these "exclusive" tracks will come to PC officially soon!
