### ISSUE TITLE
BeatSaver-Data-Set url doesn't find dat sources

### ISSUE THREAD

**Issue by alx** [elliotttate/beatsaver-laravel#65]
Hi,

I'm still interested by fetching beatsaver dataset.

Current url shown on https://beatsaver.com/ footer:

https://datbase.org/beatsaver/BeatSaver-Data-Set

Thanks,

Alex

**Comment by lolPants** [comment]
Since switching ownership the datbase dataset no longer exists. You'll have to ask the new owners to provide a new dataset.
